import Head from "next/head";
import Benefits from "../components/Benefits";
import CalcSavings from "../components/CalcSavings";
import ChatButton from "../components/ChatButton";
import FinePrint from "../components/FinePrint";
import Hero from "../components/Hero";
import MoreChoices from "../components/MoreChoices";
import QuickLinks from "../components/QuickLinks";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-[120px] mb-[60px] md:mt-[46px] ld:mt-[186px]">
        <Hero />
        <CalcSavings />
        <MoreChoices />
        <Benefits />
        <QuickLinks />
        <FinePrint />
        <ChatButton />
      </main>
    </>
  );
}
